#!/usr/bin/env bash
# Print store / TestFlight / Play checklist for the current mobile version.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MOBILE="$ROOT/apps/mobile"
VER="$(grep -E '^version:' "$MOBILE/pubspec.yaml" | awk '{print $2}')"
NAME="${VER%%+*}"
BUILD="${VER##*+}"

has() { [[ -f "$1" ]] && echo "YES" || echo "NO "; }

echo "BEVEL native store checklist — pubspec $VER (name $NAME / build $BUILD)"
echo ""
echo "Local secrets / signing"
echo "  [$(has "$MOBILE/android/app/google-services.json")] android google-services.json"
echo "  [$(has "$MOBILE/ios/Runner/GoogleService-Info.plist")] ios GoogleService-Info.plist"
echo "  [$(has "$MOBILE/android/key.properties")] android key.properties (Play upload)"
echo "  [$(has "$ROOT/secrets/firebase-service-account.json")] server service-account.json"
echo ""
echo "Pull Firebase from 1Password:"
echo "  ./scripts/mobile/pull-firebase-config.sh"
echo ""
echo "Build artifacts"
echo "  ./scripts/mobile/release.sh macos|android|ios"
echo "  Out: dist/native/$NAME/"
echo ""
echo "iOS → TestFlight"
echo "  [ ] Team + bundle com.derozic.bevel.bevelApp in Xcode"
echo "  [ ] Capabilities: Push Notifications, Associated Domains, HealthKit (optional)"
echo "  [ ] Archive with production dart-defines (release.sh / Xcode scheme)"
echo "  [ ] Distribute → App Store Connect → internal TestFlight group"
echo "  [ ] Privacy nutrition labels (notifications, identifiers; Health if enabled)"
echo "  [ ] Export compliance / encryption"
echo "  [ ] Screenshots: docs/STORE_SCREENSHOTS.md"
echo ""
echo "Android → Play internal track"
echo "  [ ] key.properties + upload keystore from 1Password"
echo "  [ ] flutter build appbundle (release.sh android)"
echo "  [ ] Play Console → Internal testing → upload AAB"
echo "  [ ] Data safety form (push tokens, optional Health Connect)"
echo "  [ ] Health Connect declaration if shipping health"
echo ""
echo "macOS Silicon (optional Gatekeeper)"
echo "  [ ] codesign + notarytool (see docs/NATIVE_RELEASE.md)"
echo "  [ ] Host zip on /download#macos"
echo ""
echo "Server push fan-out"
echo "  [ ] FIREBASE_SERVICE_ACCOUNT_PATH on API host"
echo "  [ ] curl GET /api/v1/devices/push-status  (fcmConfigured: true)"
echo "  [ ] Device QA push section: ./scripts/mobile/device-qa.sh"
echo ""
echo "When store URLs live"
echo "  [ ] Update apps/web download page #ios / #android store links"
echo "  [ ] Bump pubspec build number for every upload"
echo ""
echo "Device QA gate: docs/DEVICE_QA.md"
